version: '3'

services:
  db:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desafio_final
      MYSQL_USER: usr_xpe
      MYSQL_PASSWORD: xpe2024!@#
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql

  jupyterlab:
    image: jupyter/datascience-notebook:latest
    restart: always
    ports:
      - 8888:8888
    volumes:
      - .:/home/jovyan/work
    environment:
      JUPYTER_ENABLE_LAB: yes
      GRANT_SUDO: yes
    command: start-notebook.sh --NotebookApp.token=''
    extra_hosts:
      - "host.docker.internal:host-gateway"